### PR TITLE
feat: add leap wallet

### PR DESCRIPTION
**Pull request by himanshu-leap**
@NoahSaso can you please review this PR and let me know if I have to add anything else?
Thanks.

### CODE REVIEW

**Comment by himanshu-leap** [comment]
@NoahSaso to test the leap integration before it go live publicly, does the change need to be done in the example folder? And can you help with that?

Also, we have this - https://docs.leapwallet.io/cosmos/connect-to-leap/add-leap-to-existing-keplr-integration

**Review by noahsaso — CHANGES_REQUESTED** [review]
sweet! this looks great. i'll test it before merging it in.

i realized that the keplr keystore change event is hardcoded right now, so i just merged a PR to generalize that and move it to the wallet definition: https://github.com/NoahSaso/cosmodal/pull/10

you should merge in my changes and add the `leap_keystorechange` here so that works as expected

**Comment by himanshu-leap** [comment]
@NoahSaso Thanks for reviewing it. I have pushed the requested changes.

**Review by noahsaso — APPROVED** [review]
great, thank you! i'll publish this as v0.8.9 after i add leap to the example app

**Comment by himanshu-leap** [comment]
Thanks for merging it @NoahSaso 
Just let me know, if I can help in testing if everything works right or not.

**Pull request merged**
